import "./globals.css";
import Header from "@/app/__component/__frontend/partials/Header";
import Footer from "@/app/__component/__frontend/partials/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">

      <body>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
